// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ceiling-trend/CeilingTrendMobile.tsx": () => import("../components/mockups/ceiling-trend/CeilingTrendMobile.tsx"),
  "./components/mockups/ceiling-trend/CeilingTrendPage.tsx": () => import("../components/mockups/ceiling-trend/CeilingTrendPage.tsx"),
  "./components/mockups/ceiling-trend/PublicDashboardTabs.tsx": () => import("../components/mockups/ceiling-trend/PublicDashboardTabs.tsx"),
  "./components/mockups/ceiling-trend/PublicDashboardTabsMobile.tsx": () => import("../components/mockups/ceiling-trend/PublicDashboardTabsMobile.tsx"),
  "./components/mockups/intl-converted/IntlConvertedChart.tsx": () => import("../components/mockups/intl-converted/IntlConvertedChart.tsx"),
  "./components/mockups/legend-demo/LegendDemo.tsx": () => import("../components/mockups/legend-demo/LegendDemo.tsx"),
  "./components/mockups/login-mobile/MobileLogin.tsx": () => import("../components/mockups/login-mobile/MobileLogin.tsx"),
  "./components/mockups/login-mobile/MobileLoginCenter.tsx": () => import("../components/mockups/login-mobile/MobileLoginCenter.tsx"),
  "./components/mockups/tax-aware-comparison/TaxAwareChart.tsx": () => import("../components/mockups/tax-aware-comparison/TaxAwareChart.tsx")
};
